fixed
tsv1/vedro pull request #49
Opened 2023-04-05 04:26 UTC by iri6e4k0

2023-04-05 10:36 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_reporter.py
> +    tb_length_long_str: int = 1000
точно стоит по умолчанию его выставлять? 

Может по умолчанию отключено оставить?

2023-04-05 10:40 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def print_scope(self, scope: Dict[str, Any], length_long_str: int = 1000) -> None:
зачем по умолчанию 1000?

2023-04-05 10:42 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def cut_str(self, string: str, length: int, separator: str = "...") -> str:
выглядит как независящее от RichPrinter

даже self не используется. Мю вынести отдельно лучше?

2023-04-05 10:43 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def fold_long_strings(self, input_str: str, length_long_str: int) -> str:
fold / cut по разному называется везде. 

Кажется лучше привести к единому термину.

2023-04-05 10:46 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def fold_long_strings(self, input_str: str, length_long_str: int) -> str:
Хотя оно по разному применяется - к строкам кат а к многострочному тексту fold.

может это отразить в названии что тут строка разбивается и построчно сокращение идет?

2023-04-05 10:49 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def fold_long_strings(self, input_str: str, length_long_str: int) -> str:
Тоже как то не сильно зависит от RichPrinter

может отдельным хелпером-функцией оформить?

2023-04-05 10:50 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> +    def print_scope_val(self, val: Any, length_long_str: int = 1000) -> None:
точно должно быть значение по умолчанию?

2023-04-05 10:52 UTC, ko10ok commented on tests/plugins/director/rich/reporter/test_rich_reporter_failed.py
> +            call.print_scope(scope, length_long_str=1000)
зачем явно это задавать если оно было задано по умолчанию в 1000?

мб лучше по умолчанию не обрезать строки?

2023-04-05 10:52 UTC, ko10ok commented on tests/plugins/director/rich/printer/test_rich_printer.py
> +def test_print_scope_val_with_long_str(*, printer: RichPrinter, console_: Mock):
кажется не хватает теста для значения по умолчанию.

2023-04-05 10:53 UTC, ko10ok commented on tests/plugins/director/rich/printer/test_rich_printer.py
> +def test_print_scope_val_with_long_str(*, printer: RichPrinter, console_: Mock):
и вероятно не хватает еще одного теста на строку с несколькими строками (что он не полностью образает а длину строки без(между) переносами)

2023-04-10 07:42 UTC, tsv1 requested changes

2023-04-10 07:42 UTC, tsv1 commented on vedro/plugins/director/rich/_rich_printer.py
> -        self._console.print(val)
`print` поддерживает параметр `overflow`, поэтому можно просто прокинуть его из конфига:

```python
class RichReporter(PluginConfig):
    scope_overflow: OverflowMethod = "ignore"
```

```python
def print_scope_val(self, val: Any, *, overflow: OverflowMethod = "ignore") -> None:
    self._console.print(val, overflow=overflow)
```

2023-04-11 06:31 UTC, iri6e4k0 commented on vedro/plugins/director/rich/_rich_printer.py
> -        self._console.print(val)
я тогда попробую проверить как сокращает с этим параметром локально, если подойдет то просто надо будет прокидывать из конфига вместо всей этой штуки https://gitlab.2gis.ru/webdev/urbi-geo/-/merge_requests/989/diffs

2023-04-27 05:36 UTC, ko10ok commented on vedro/plugins/director/rich/_rich_printer.py
> -        self._console.print(val)
он построчно сокращает строки? 

Стоит этот момент учесть - мы построчно сокращаяем (с учетом \n) а не просто строку целиком

2023-04-28 11:23 UTC, iri6e4k0 commented on vedro/plugins/director/rich/_rich_printer.py
> -        self._console.print(val)
@ko10ok @tsv1 
вообщем проверила локально выглядит неинформативно:
сrop
"wkt": "POLYGON((55.351418 25.317797,55.35352 25.32024 
fold 
"wkt": "POLYGON((55.351418 25.317797,55.35352 25.320245,55.353778 25.320566,55.353955 25.320876,55.354098 25.3214,55.355115 25.325816,55.355144 25.326
    }
ellipsis
"wkt": "POLYGON((55.351418 25.317797,55.35352 25.320245,55.353778 25.320566,55.353955 25.320876,55.354098 25.3214,55.355115 25.325816,55.355144 25.32…
    }
Построчно только первую строку сокращает
"wkt": "POLYGON((55.351418 25.317797,55.35352 25.3202…  

так что предлагаю оставить то что сделано

2023-05-04 07:55 UTC, tsv1 requested changes

2023-05-04 07:55 UTC, tsv1 commented on vedro/plugins/director/rich/_rich_reporter.py
> +    tb_cut_scope: bool = False
Префикс `tb_` означает traceback.

Давай переименуем и оставим один параметр:

```python
scope_width: int = -1
```

Если `-1` — не обрезаем, если >=0 — обрезаем до значения

2023-05-18 18:14 UTC, tsv1 commented
LGTM

2023-05-18 18:14 UTC, merged